//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gibdd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Fines = new HashSet<Fines>();
        }
    
        public int id { get; set; }
        public string VIN { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> IdColor { get; set; }
        public Nullable<int> IdEngineType { get; set; }
        public Nullable<int> TypeOfDrive { get; set; }
        public Nullable<int> IdRegionCode { get; set; }
    
        public virtual CarColors CarColors { get; set; }
        public virtual engine_types engine_types { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual RegionCodes RegionCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fines> Fines { get; set; }
    }
}
