//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gibdd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeHistory
    {
        public int id { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IdLicence { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Licences Licences { get; set; }
        public virtual Status Status { get; set; }
    }
}
