//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gibdd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drivers()
        {
            this.Licences = new HashSet<Licences>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Middlename { get; set; }
        public int PassportSerial { get; set; }
        public int PassportNumber { get; set; }
        public int Postcode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public Nullable<int> id_Workplace { get; set; }
        public Nullable<int> id_Adress { get; set; }
        public Nullable<int> id_Licence { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Workplace Workplace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licences> Licences { get; set; }
    }
}
