//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gibdd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fines
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> IdLicence { get; set; }
        public Nullable<int> IdCars { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Licences Licences { get; set; }
    }
}
