//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gibdd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionCodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegionCodes()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int id { get; set; }
        public string RegionNameEN { get; set; }
        public string RegionNameRU { get; set; }
        public int SubjectCode { get; set; }
        public int RegionCode { get; set; }
        public int OKATO { get; set; }
        public string ISO3166_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
    }
}
